### ISSUE TITLE
Dependencies out of date

### ISSUE THREAD

**Issue by stephenwade** [lydell/eslump#17]
Hi there! I've noticed that most of the dependencies of this project are out of date, including one that is causing a deprecation warning in projects that depend on this one.

```
npm WARN deprecated babel-eslint@8.2.6: babel-eslint is now @babel/eslint-parser.
This package will no longer receive updates.
```

Would you be open to pull requests to update the dependencies?

**Comment by lydell** [comment]
Yes! 🙏 

I haven’t had the need for this project for some time, so I haven’t kept anything up-to-date.

**Comment by stephenwade** [comment]
@lydell I've created #18 to update all dependencies, move from Travis CI to GitHub Actions, and clean up a couple other minor issues.
