### ISSUE TITLE
Error: Cannot find module 'shift-codegen/dist/token_stream'

### ISSUE THREAD

**Issue by mysticatea** [lydell/eslump#5]
If I use `require("eslump")` then it throws `Cannot find module 'shift-codegen/dist/token_stream'`.

https://github.com/shapesecurity/shift-codegen-js/commit/85249fc5e6db5f6a0ef787992c009c18676c53a6 seemed to move `dist/token_stream.js` to `dist/token-stream.js`

**Comment by lydell** [comment]
Hehe, this is what happens when you rely on hacks :) Should be easy to fix, though. We should lock down the versions of all dependencies where we rely on non-public stuff as well. If you want to make a PR that would be awesome. Otherwise I’ll try to look at this tonight.
